Living Wage KE
CodeForAfrica/LivingWage.KE pull request #1
Opened 2019-03-08 05:41 UTC by puritybirir

##### What does this PR do?
- Add the correct data sets for Living Wage KE
- Create an introduction to Living Wage KE
- Make UI Changes ie font-size, font-type, colors and other small additions

##### Description of Task to be completed?
- Create a Living Wage Calculator for Living Wage KE

##### Any background context you want to provide?
- The previous Calculator was designed for South Africa

##### What are the relevant Pivotal Tracker stories?
- #164323157
- #164323542
- #164323521
- #164322752
- #164208259

##### Questions?
- None

##### Screenshots/Screencasts?
   **Introduction**
![living wage](https://user-images.githubusercontent.com/19901599/54009885-a9fa9580-417d-11e9-82c7-68721a3abc78.gif)
   **Calculator**
![calculator](https://user-images.githubusercontent.com/19901599/54009915-c8609100-417d-11e9-840b-2123b8b69677.gif)

2019-03-08 09:39 UTC, kilemensi requested changes
Code wise seems cool @puritybirir, but:

 1. Does someone need to sit through the intro **every time** they visit the site? No skip, fast forward or even pause and rewind if you've missed a word?
 2. I think the arrow down should be clickable. Clicking it should take me to the calculator.
![screenshot from 2019-03-08 12-37-41](https://user-images.githubusercontent.com/1779590/54020507-fdc9a680-419e-11e9-9aa7-3a822fc2d4d7.png)
 3. The share buttons seem broken to me.
![screenshot from 2019-03-08 12-26-48](https://user-images.githubusercontent.com/1779590/54020489-f4403e80-419e-11e9-978d-eedf3c7ed8d0.png)

2019-03-08 09:39 UTC, kilemensi commented on css/styles.css
> +    font-family: 'Montseratt';
Where do we include `Montseratt`?

2019-03-08 09:39 UTC, kilemensi commented on css/styles.css
> +    font-family: 'sans-serif';
Shouldn't it be one of the imported fonts?

2019-03-08 09:39 UTC, kilemensi commented on css/styles.css
> +
New line

2019-03-11 07:05 UTC, puritybirir commented
> Code wise seems cool @puritybirir, but:
> 
> 1. Does someone need to sit through the intro **every time** they visit the site? No skip, fast forward or even pause and rewind if you've missed a word?
> 2. I think the arrow down should be clickable. Clicking it should take me to the calculator.
>    ![screenshot from 2019-03-08 12-37-41](https://user-images.githubusercontent.com/1779590/54020507-fdc9a680-419e-11e9-9aa7-3a822fc2d4d7.png)
> 3. The share buttons seem broken to me.
>    ![screenshot from 2019-03-08 12-26-48](https://user-images.githubusercontent.com/1779590/54020489-f4403e80-419e-11e9-978d-eedf3c7ed8d0.png)

Resolved

2019-03-11 10:30 UTC, kilemensi requested changes
@puritybirir:

 1. Ensure all resources are loaded via `//domain`, you're still mixing `http://` and `https://`,
 2. The KSH 8000 maximum seems a bit too low (both month and week will show red). But it's up to the data team I guess.
![Screenshot from 2019-03-11 13-25-59](https://user-images.githubusercontent.com/1779590/54117352-98c1bb00-4401-11e9-8a77-d8d44a30aae7.png)


Other than that, I think it's good to go. :+1: .

-----------------------

PS: The broken Twitter and Facebook buttons was because of Firefox blocking [content](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

2019-03-11 10:30 UTC, kilemensi commented on index.html
>    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
Repeated font-awesome loading.

2019-03-14 05:50 UTC, kilemensi approved these changes

2019-03-14 05:50 UTC, kilemensi commented on index.html
> +          <p>There are around 1.8 -2 million domestic workers in Kenya</p>
Missing space before 2 million: `There are around 1.8 - 2`

2019-03-14 05:50 UTC, kilemensi commented on index.html
> +  <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"> -->
Instead of commenting out, remove the stuff we no longer use.

2019-03-14 12:37 UTC, puritybirir commented
> @puritybirir:
> 
> 1. Ensure all resources are loaded via `//domain`, you're still mixing `http://` and `https://`,
> 2. The KSH 8000 maximum seems a bit too low (both month and week will show red). But it's up to the data team I guess.
>    ![Screenshot from 2019-03-11 13-25-59](https://user-images.githubusercontent.com/1779590/54117352-98c1bb00-4401-11e9-8a77-d8d44a30aae7.png)
> 
> Other than that, I think it's good to go. 👍 .
> 
> PS: The broken Twitter and Facebook buttons was because of Firefox blocking [content](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

Fixing the resources ASAP. This is the data the team was using based on the assumptions they created

2019-03-15 09:33 UTC, kilemensi reviewed
Sources missing for: **Transportation Cost**, **Communications Cost**, **Recreation Cost**, and **Other Costs** @puritybirir

2019-03-15 09:33 UTC, kilemensi commented on css/styles.css
>  @import url(http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300);
Update to `https`

2019-03-15 09:33 UTC, kilemensi commented on index.html
>    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
Update to `https` (& also the link to include `bootstrap.min.js`)

2019-03-22 08:07 UTC, merged